version: '3'

services:
    mariadb:
        build: "./requirements/mariadb"
        container_name: mariadb
        restart: always
        env_file:
            - ".env"
        volumes:
            - db:/var/lib/mysql
        expose:
            - "3306"
        networks:
            - intra
    nginx:
        build: "./requirements/nginx"
        container_name: nginx
        restart: always
        env_file:
            - ".env"
        volumes:
            - wp:/var/www/html
        ports:
            - "443:443"
        networks:
            - intra
    wordpress:
        build: "./requirements/wordpress"
        container_name: wordpress
        restart: always
        volumes:
            - wp:/var/www/html
        expose:
            - "9000"
        networks:
            - intra

networks:
    intra:
        driver: bridge

volumes:
    db:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/yjung/data/db'
    wp:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/yjung/data/wp'

